### ISSUE TITLE
[incredibly petty complaint] the bpm in exported .wavs is ever so slightly off

### ISSUE THREAD

**Issue by Sobsz** [johnnesky/beepbox#11] opened 2020-06-10 14:23 UTC
very original test track: https://beepbox.co/#8n10s7k2l00e0ot4Im0a7g0oj01i0r1o3T0v1L4u00q0d1f8y0ziC0w5c0h0bllllllllwp1tFE-a4R_irbWjnW4x8FE_qqHCZ7WPg
it should be exactly 40 seconds long (25 bars * 8 beats each / 300 bpm = 2/3 minutes = 40 seconds) but it ends up being 39 + 36900 samples, 7200 less than needed (aka missing 36 samples per beat)
that plus when you play a metronome next to it it goes noticeably off-sync within about 10 seconds
slower tempos make the problem less pronounced but it's still there (150 bpm goes off-sync in like 30 seconds which is not 2 * 10 seconds?)
not much of a problem usually, but when you wanna sync a video to it it can be pretty painful

i'm guessing there's some sort of rounding error, where the smallest beat subdivision is defined to be an integer amount of samples (while for perfect bpm compliance™ you'd have to calculate directly from the bpm every time i think? like if you wanted to have 1000 subdivisions per second (44.1 samples) you'd have to do `round(44100 * subdivision_count / 1000)` and not `round(44100 / 1000) * subdivision_count` so the rounding happens as late as possible)
when recording via stereo mix the problem doesn't seem to be present, probably because it uses the system clock or something

i don't expect this to get fixed because honestly that's too much effort for too little benefit probably

flac files of the export and the manual recording just in case: [exported vs recorded via stereo mix.zip](https://github.com/johnnesky/beepbox/files/4759086/exported.vs.recorded.via.stereo.mix.zip)

**Comment by johnnesky** [comment] 2020-06-12 06:49
Hi! You've correctly deduced the cause of the discrepancy. It's not straightforward to fix, but it's not impractical either, I'm afraid I just haven't had the time to prioritize that fix yet, but it's on my to-do list!

**Comment by johnnesky** [comment] 2020-11-29 21:05
Fixed in https://github.com/johnnesky/beepbox/commit/46a2f1ada41a1b6946ff9d2420da3d6c427b4a4f

**Closed by johnnesky** 2020-11-29 21:05 UTC
